version: '3.8'
services:

  ### PostgreSQL database for JDBC example
  db-jdbc:
    container_name: produtos_aula
    image: postgres:latest # Usando a imagem oficial do PostgreSQL
    environment:
      POSTGRES_DB: db_produtos # Nome do banco de dados
      POSTGRES_USER: admin # Usuário do banco
      POSTGRES_PASSWORD: admin # Senha do banco
    ports:
      - "5432:5432" # Mapeamento de porta do host para o container
    expose:
      - 5432 # Expondo a porta para outros serviços dentro do Docker Compose
    command: -p 5432 # Configurando a porta padrão do PostgreSQL
    volumes:
      - jdbc-data-produtos:/var/lib/postgresql/data # Volume para persistência dos dados

volumes:
  jdbc-data-produtos: # Volume nomeado para persistência de dados do PostgreSQL

#  docker exec -it produtos_aula psql -U admin -d db_produtos
